<a href="https://colab.research.google.com/github/aliyurs/ArewaDS-Deep-Learning/blob/main/week1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arewa Data Science Academy

Deep Learning Cohort 2.0

Name: Aliyu Rabiu Shuaibu

Email: aliyursringim@gmail.com

Title: Week 1 Solution

Exercise Solution

Question 1 Random Tensor

In [1]:
# Import torch
import torch

# Create Random Tensor shape (7, 7)

A = torch.rand(size=(7, 7))
A, A.shape

(tensor([[0.5478, 0.8305, 0.3144, 0.0163, 0.1591, 0.6310, 0.6378],
         [0.6567, 0.3081, 0.2100, 0.3089, 0.2708, 0.3536, 0.9159],
         [0.8748, 0.1498, 0.1744, 0.4933, 0.8811, 0.4637, 0.2521],
         [0.9235, 0.6092, 0.7173, 0.9661, 0.1118, 0.5492, 0.1502],
         [0.4237, 0.0281, 0.7288, 0.5942, 0.6656, 0.0818, 0.0365],
         [0.4918, 0.9861, 0.6971, 0.1599, 0.6443, 0.1971, 0.6929],
         [0.4138, 0.8270, 0.7020, 0.3851, 0.5637, 0.5769, 0.9509]]),
 torch.Size([7, 7]))

Matrix multiplication on the tensor from 2

In [2]:
# Create another random tensor
B = torch.rand(size=(1, 7))

#Perfor Matrix Multiplication
C = torch.matmul(A, B.T)
C, C.shape

(tensor([[0.7417],
         [0.6839],
         [1.0371],
         [0.8673],
         [1.0075],
         [1.2296],
         [1.3409]]),
 torch.Size([7, 1]))

Set Random seed to 0 and do 2 & 3 over again

In [3]:
# Set Manual Seed
torch.manual_seed(0)

# Create two random tensors
A = torch.rand(size=(7, 7))
B = torch.rand(size=(1, 7))

# Matrix multiply tensors
C = torch.matmul(A, B.T)
C, C.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [4]:
#Set random seed on the GPU
torch.cuda.manual_seed(1234)

Creat two random tensors of shape (2, 3) and send to GPU. Set torch.manual_seed(1234)

In [8]:
# Set Random Seed
torch.manual_seed(1234)

#Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensor on GPU

tensor_D = torch.rand(size=(2,3)).to(device)
tensor_E = torch.rand(size=(2,3)).to(device)
tensor_D, tensor_E

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

Perform MAtrix Multiplication of 6 above

In [9]:
# Perform matmul on tensor_D and Tensor_E
tensor_F = torch.matmul(tensor_D, tensor_E.T)
tensor_F, tensor_F.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

Find Maximum and minimum values of the output of 7 above

In [10]:
# Find Max
max = torch.max(tensor_F)

# Find Min
min = torch.min(tensor_F)
max, min

(tensor(0.5617), tensor(0.3647))

Find the maximum and minimum index values of the output of 7.

In [11]:
# Find Arg Max
arg_max = torch.argmax(tensor_F)

# Find Arg Min
arg_min = torch.argmin(tensor_F)
arg_max, arg_min

(tensor(3), tensor(0))

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [12]:
# Set seed
torch.manual_seed(7)

# Create Random tensor
tensor_G = torch.rand(size=(1, 1, 1, 10))

#Remove Single Dimension
tensor_H = tensor_G.squeeze()

# Print out tensors
print(tensor_G, tensor_G.shape)
print(tensor_H, tensor_H.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
